import Dexie from "dexie";

export interface Order {
  id?: number; // Auto-generated by Dexie
  tableNumber: number;
  items: { name: string; quantity: number; price: number }[];
  totalPrice: number;
  status: string;
  createdAt: Date;
}

export interface SyncQueueItem {
  id?: number; // Auto-generated by Dexie
  operation: string;
  data: Order;
}

const db = new Dexie("POSDB");

// Define the tables and schema
db.version(1).stores({
  orders: "++id, tableNumber, items, totalPrice, status, createdAt", // Orders table
  syncQueue: "++id, operation, data", // Sync queue table
});

export default db;
