import Dexie from "dexie";

export interface Order {
  id?: number; // Auto-generated by Dexie
  orderId?: string;
  tableNumber: number;
  items: { name: string; quantity: number; price: number }[];
  totalPrice: number;
  status:  "open" | "completed" | "cancelled";
  createdAt: Date;
}

export interface SyncQueueItem {
  id?: number; // Auto-generated by Dexie
  operation: string;
  data: Order;
}

const db = new Dexie("POSDB");

// Define the tables and schema
db.version(1).stores({
  orders: "++id, orderId, tableNumber, items, totalPrice, orderStatus, createdAt",
  syncQueue: "++id, operation, data, data.orderId",
  menu: "++id, superCategory, subCategory, items", // Store menu items
});

export default db;
